NumPy (Numerical Python) is a high-performance Python library for handling multi-dimensional arrays (ndarray) and performing fast mathematical, statistical, linear algebra, broadcasting, random generation, reshaping, indexing, and scientific computing operations, forming the foundation for data processing and machine learning libraries

Creation of numpy array

In [ ]:
#IMPORT NUMPY
import numpy as np

a=np.array([1,2,3])
print(a)



[1 2 3]


In [ ]:
#2D & 3D
b=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
np.array([1,2,3],dtype=float) #float,bool,complex..
# np.array([4,5,6],bool)

array([1., 2., 3.])

In [ ]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#np.ones and np.zeros,np.random # used for value initialization
np.ones((3,4))
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np,random
np.random.random((2,4))

array([[0.10033082, 0.75923847, 0.8041279 , 0.38467792],
       [0.42837817, 0.88742959, 0.27384726, 0.11989979]])

In [ ]:
#np.linspace (lowr_range,upper_range,number of item to generate)
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
#np.identity (metrix)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Array Attributes

In [ ]:
a1=np.arange(10,dtype=np.int32) # 1D array & vector ,by default we have int64
a2=np.arange(12,dtype=float).reshape(3,4) # metrix
a3=np.arange(16).reshape(2,2,2,2) # tensors



In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
#ndim (number of diamentinal array)
a1.ndim
a2.ndim
a3.ndim

4

In [ ]:
# shape (it's tell the number exist in each diamention)
print(a1.shape) #10 items
a1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [ ]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
print(a3.shape)
a3

(2, 2, 2, 2)


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# size (its tell me the items in side the array)
print(a3.size)
a3

16


array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
# itemsize (its tell me about the each item occupy the space in memory)
a2.itemsize

8

In [ ]:
a3.itemsize

8

In [ ]:
a1.itemsize

4

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


Changing datatype

In [ ]:
#astype (optimize the memory) space reduction eg
a3.dtype

dtype('int64')

In [ ]:
a3.astype(np.int32)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]], dtype=int32)

Array operation

In [ ]:
a1=np.arange(10).reshape(2,5)
a2=np.arange(12,22).reshape(2,5)
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a2

array([[12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

In [ ]:
#scalar operation
# arthmetic
# -,+,%,/,*,**...example
a1-2


array([[-2, -1,  0,  1,  2],
       [ 3,  4,  5,  6,  7]])

In [ ]:
# relational,<,>,==
a1 == 8

array([[False, False, False, False, False],
       [False, False, False,  True, False]])

In [ ]:
# vector operation..ensure that both are in same diamentions like 2*5 ,2*5
a1+a2  #_,*,**,%..

array([[12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

Array function

In [ ]:
# Array function creation
a3=np.random.random((3,3))
a3=np.round(a3*100)
a3

array([[40., 69., 41.],
       [30., 19., 94.],
       [48., 68., 34.]])

In [ ]:
#max,min,sum,prod
np.max(a3)

np.float64(94.0)

In [ ]:
np.min(a3)

np.float64(19.0)

In [ ]:
np.sum(a3)

np.float64(443.0)

In [ ]:
np.prod(a3)

np.float64(672860006092800.0)

In [ ]:
# 0-> col and 1->row ..perticular row ,columns min/max/sum/prod
np.max(a3,axis=0)

array([48., 69., 94.])

In [ ]:
np.sum(a3,axis=0)

array([118., 156., 169.])

In [ ]:
# mean/median/std/var
np.mean(a3)

np.float64(49.22222222222222)

In [ ]:
np.median(a3,axis=1)

array([41., 30., 48.])

In [ ]:
# trigonomoetric functions ,sin,cos,tan...
np.sin(a3)

array([[ 0.74511316, -0.11478481, -0.15862267],
       [-0.98803162,  0.14987721, -0.24525199],
       [-0.76825466, -0.89792768,  0.52908269]])

In [ ]:
# dot product
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(4,3)

np.dot(a4,a5)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents(exp)
np.log(a4)
np.exp(a5)


/tmp/ipykernel_1654/1852478673.py:2: RuntimeWarning: divide by zero encountered in log
  np.log(a4)


array([[1.62754791e+05, 4.42413392e+05, 1.20260428e+06],
       [3.26901737e+06, 8.88611052e+06, 2.41549528e+07],
       [6.56599691e+07, 1.78482301e+08, 4.85165195e+08],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09]])

In [ ]:
#round/floor/ceil
np.round(np.random.random((2,3))*100)

array([[10., 92., 26.],
       [ 9., 68., 89.]])

Indexing and  slicing

Indexing in NumPy is the method used to access or modify specific elements, rows, or blocks within an array

Slicing in NumPy is the process of extracting a specific range or subset of elements from an array

In [ ]:
a1=np.arange(10)
a2=np.arange(12).reshape(4,3)
a3=np.arange(8).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1[-2]  # negative(-1,-2..) right to left ..positive(0,1,2..) left to right

np.int64(8)

In [ ]:
a2[2,1] # if we need to select the number 7 so we need to write row vs column(2,1)

np.int64(7)

In [ ]:
a2[3,2]

np.int64(11)

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1] # if we need to pick 5 in 3D we need to provide 3 numbers[number of metrix,row number ,columns number]

np.int64(5)

In [ ]:
a3[1,1,1]

np.int64(7)

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5] # if we want to select 2,3,4 then we need to write [2:5]=> [include:exclude]

array([2, 3, 4])

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2[0,:] # first row all columns for that we use ":"

array([0, 1, 2])

In [ ]:
a2[:,2] #":" all  numbers in a column

array([ 2,  5,  8, 11])

In [ ]:
a2[2:,1:3]

array([[ 7,  8],
       [10, 11]])

In [ ]:
a2[::3,::2] #[: all range :3jump,: all range :2 jump]

array([[ 0,  2],
       [ 9, 11]])

In [ ]:
a2[::3,1::]

array([[ 1,  2],
       [10, 11]])

In [ ]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a2[2,::2]

array([6, 8])

In [ ]:
a2[:2,:3]

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [ ]:
a3[0::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0,1]

array([3, 4, 5])

In [ ]:
a3[1,:,1]

array([10, 13, 16])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])