# 📘 NumPy Quick Reference Guide

A concise cheat sheet of commonly used NumPy functions for quick revision and explanation.

---

## 🔹 Array Operations
- `np.sort()` – Sorts elements of an array in ascending order  
- `np.append()` – Adds values to the end of an array  
- `np.concatenate()` – Joins two or more arrays along a given axis  
- `np.unique()` – Returns sorted unique elements  

---

## 🔹 Shape Manipulation
- `np.expand_dims()` – Expands array shape by adding a new axis  
- `np.flip()` – Reverses the order of elements  

---

## 🔹 Conditional & Indexing
- `np.where()` – Returns indices where condition is true  
- `np.argmax()` – Returns index of maximum value  
- `np.isin()` – Checks if elements are present in another array  

---

## 🔹 Mathematical & Statistical Functions
- `np.cumsum()` – Computes cumulative sum  
- `np.percentile()` – Computes specified percentile  
- `np.histogram()` – Computes frequency distribution  
- `np.corrcoef()` – Computes correlation coefficient matrix  

---

## 🔹 Array Modification
- `np.put()` – Replaces elements at specified indices  
- `np.delete()` – Removes elements from array  
- `np.clip()` – Limits values within a specified range  

---

## 🔹 Set Operations
- `np.union1d()` – Union of two arrays (unique values)  
- `np.intersect1d()` – Intersection (common elements)  
- `np.setdiff1d()` – Difference (elements in first not in second)  
- `np.setxor1d()` – Symmetric difference (non-common elements)  
- `np.in1d()` – Tests whether each element is in another array  

np.sort

return a sorted copy of an array

In [1]:
import numpy as np
a=np.random.randint(1,100,50)
print(a)


[46 67 24 17 81  1 71 88 12 34 89 12 75  7 54  1 39 14  8 78 39 23 75 14
 72 95 89 62 90 15 11 38 91 93 49 11  9 64 55 65 49 15 34 44 87 36 94 53
 53 13]


In [2]:
#2D
b=np.random.randint(1,100,24).reshape(6,4)
print(b)

[[ 3 13 89 62]
 [13 33 95 31]
 [97 26 20 50]
 [21 82  8  8]
 [27 89 89 28]
 [75 46 50 28]]


In [3]:
np.sort(a) # accending order

array([ 1,  1,  7,  8,  9, 11, 11, 12, 12, 13, 14, 14, 15, 15, 17, 23, 24,
       34, 34, 36, 38, 39, 39, 44, 46, 49, 49, 53, 53, 54, 55, 62, 64, 65,
       67, 71, 72, 75, 75, 78, 81, 87, 88, 89, 89, 90, 91, 93, 94, 95])

In [4]:
np.sort(a)[::-1] # decending order

array([95, 94, 93, 91, 90, 89, 89, 88, 87, 81, 78, 75, 75, 72, 71, 67, 65,
       64, 62, 55, 54, 53, 53, 49, 49, 46, 44, 39, 39, 38, 36, 34, 34, 24,
       23, 17, 15, 15, 14, 14, 13, 12, 12, 11, 11,  9,  8,  7,  1,  1])

In [5]:
np.sort(b,axis=0) #columns wise sorting

array([[ 3, 13,  8,  8],
       [13, 26, 20, 28],
       [21, 33, 50, 28],
       [27, 46, 89, 31],
       [75, 82, 89, 50],
       [97, 89, 95, 62]])

In [6]:
np.sort(b,axis=1) #row wise sorting

array([[ 3, 13, 62, 89],
       [13, 31, 33, 95],
       [20, 26, 50, 97],
       [ 8,  8, 21, 82],
       [27, 28, 89, 89],
       [28, 46, 50, 75]])

np.append

the numpy.append() appends value along the mentioned axis at the end of the array

In [7]:
np.append(a,200)

array([ 46,  67,  24,  17,  81,   1,  71,  88,  12,  34,  89,  12,  75,
         7,  54,   1,  39,  14,   8,  78,  39,  23,  75,  14,  72,  95,
        89,  62,  90,  15,  11,  38,  91,  93,  49,  11,   9,  64,  55,
        65,  49,  15,  34,  44,  87,  36,  94,  53,  53,  13, 200])

In [8]:
b

array([[ 3, 13, 89, 62],
       [13, 33, 95, 31],
       [97, 26, 20, 50],
       [21, 82,  8,  8],
       [27, 89, 89, 28],
       [75, 46, 50, 28]])

In [9]:
# if we want to add ones at the end(columns) of the 2d array
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[ 3., 13., 89., 62.,  1.],
       [13., 33., 95., 31.,  1.],
       [97., 26., 20., 50.,  1.],
       [21., 82.,  8.,  8.,  1.],
       [27., 89., 89., 28.,  1.],
       [75., 46., 50., 28.,  1.]])

np.concatenate

np.concatenate() function concatenate a sequence of array aling an existing axis


In [10]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print("print the c array values",c)
print("print the d araay values",d)

print the c array values [[0 1 2]
 [3 4 5]]
print the d araay values [[ 6  7  8]
 [ 9 10 11]]


In [11]:
np.concatenate((c,d),axis=0) # row  wise

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [12]:
np.concatenate((c,d),axis=1) # columns wise

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

np.unique() we can get the unique values from an array given as parameter in np.unique() method

In [13]:
# find unique numbers
e=np.array([1,1,2,2,3,3,4,4,4,5,5,5,6,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

NP.expand_dims

with the help of numpy.expland_dimns() method we can get the expanded dimensions of an array

In [14]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [15]:
a.shape

(50,)

In [16]:
np.expand_dims(a,axis=0)

array([[46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1,
        39, 14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38,
        91, 93, 49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53,
        53, 13]])

In [17]:
np.expand_dims(a,axis=0).shape

(1, 50)

In [18]:
np.expand_dims(a,axis=1).shape

(50, 1)

np.where

the numpy.where() finction return the indices of elements in an input array where the given condition is satisfied

In [19]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [20]:
#find all indices with value greater than 50
np.where(a>50)

(array([ 1,  4,  6,  7, 10, 12, 14, 19, 22, 24, 25, 26, 27, 28, 32, 33, 37,
        38, 39, 44, 46, 47, 48]),)

In [21]:
# replace all values >50 with 0
#np.where(condition,true,false)
np.where(a>50,0,a)

array([46,  0, 24, 17,  0,  1,  0,  0, 12, 34,  0, 12,  0,  7,  0,  1, 39,
       14,  8,  0, 39, 23,  0, 14,  0,  0,  0,  0,  0, 15, 11, 38,  0,  0,
       49, 11,  9,  0,  0,  0, 49, 15, 34, 44,  0, 36,  0,  0,  0, 13])

In [22]:
# replace all even number to 0
np.where(a%2==0,0,a)

array([ 0, 67,  0, 17, 81,  1, 71,  0,  0,  0, 89,  0, 75,  7,  0,  1, 39,
        0,  0,  0, 39, 23, 75,  0,  0, 95, 89,  0,  0, 15, 11,  0, 91, 93,
       49, 11,  9,  0, 55, 65, 49, 15,  0,  0, 87,  0,  0, 53, 53, 13])

np.argmax

the numpy.argmax() function return indices of the MAX ELEMENT of the array in a perticular axis

In [23]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [24]:
np.argmax(a)

np.int64(25)

In [25]:
b

array([[ 3, 13, 89, 62],
       [13, 33, 95, 31],
       [97, 26, 20, 50],
       [21, 82,  8,  8],
       [27, 89, 89, 28],
       [75, 46, 50, 28]])

In [26]:
np.argmax(b,axis=0) # columnn wise

array([2, 4, 1, 0])

In [27]:
np.argmin(a)

np.int64(5)

np.cumsum

used when we want to compute the cumulative sum of array elemrnt  over given axis




In [28]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [29]:
np.cumsum(a)

array([  46,  113,  137,  154,  235,  236,  307,  395,  407,  441,  530,
        542,  617,  624,  678,  679,  718,  732,  740,  818,  857,  880,
        955,  969, 1041, 1136, 1225, 1287, 1377, 1392, 1403, 1441, 1532,
       1625, 1674, 1685, 1694, 1758, 1813, 1878, 1927, 1942, 1976, 2020,
       2107, 2143, 2237, 2290, 2343, 2356])

In [30]:
b

array([[ 3, 13, 89, 62],
       [13, 33, 95, 31],
       [97, 26, 20, 50],
       [21, 82,  8,  8],
       [27, 89, 89, 28],
       [75, 46, 50, 28]])

In [31]:
np.cumsum(b)

array([   3,   16,  105,  167,  180,  213,  308,  339,  436,  462,  482,
        532,  553,  635,  643,  651,  678,  767,  856,  884,  959, 1005,
       1055, 1083])

In [32]:
np.cumsum(b,axis=1)

array([[  3,  16, 105, 167],
       [ 13,  46, 141, 172],
       [ 97, 123, 143, 193],
       [ 21, 103, 111, 119],
       [ 27, 116, 205, 233],
       [ 75, 121, 171, 199]])

In [33]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [34]:
np.cumprod(a)

array([                  46,                 3082,                73968,
                    1257456,            101853936,            101853936,
                 7231629456,         636383392128,        7636600705536,
            259644423988224,    23108353734951936,   277300244819423232,
        2350774287747190784, -1991324059479216128,  3148965230379638784,
        3148965230379638784, -6317564531160948736,  3787816932294475776,
       -6590952689063297024,  2414524316930277376,  1932727991733059584,
        7559255662441267200, -4904891601901060096,  5118493868223365120,
        -403322962108743680, -1422193252911546368,  2552009006839234560,
       -7796138239353421824,  -676166740845002752,  8304242961034510336,
        -887047797168144384,  3185671855029616640, -5251766371657711616,
       -8798926647718838272, -6872292042903388160, -1808236177099063296,
        2172618479817981952, -8526369881325568000, -7781741630167449600,
       -7751115970726330368,  7576942982310395904, 

np.pecentile

numpy.percentle() function used to compute the nth percentile of the given data (array elements) along the specified axis

In [35]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [36]:
np.percentile(a,100)

np.float64(95.0)

In [37]:
np.percentile(a,0)

np.float64(1.0)

In [38]:
np.percentile(a,50)

np.float64(47.5)

In [39]:
np.median(a)

np.float64(47.5)

np.histogram



In [40]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([ 5, 10,  2,  6,  4,  4,  4,  5,  5,  5]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

**np.corrcoef**

return pearson product moment coreelation coefficients(relationship between two features )

In [41]:
# its compare both salary->salary=1 ,salary -> experience=0.2773501..
salary=np.array([20000,30000,40000,25000,35000])
experience=np.array([1,2,3,4,2])
np.corrcoef(salary,experience)

array([[1.       , 0.2773501],
       [0.2773501, 1.       ]])

np.isin

search multiple items at a time in given array



In [42]:
items=[10,20,30,40,50,60,70,80,90,100]
np.isin(a,items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

np.flip

its change the order but its hold the same shape


In [43]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [44]:
np.flip(a)

array([13, 53, 53, 94, 36, 87, 44, 34, 15, 49, 65, 55, 64,  9, 11, 49, 93,
       91, 38, 11, 15, 90, 62, 89, 95, 72, 14, 75, 23, 39, 78,  8, 14, 39,
        1, 54,  7, 75, 12, 89, 34, 12, 88, 71,  1, 81, 17, 24, 67, 46])

In [45]:
b

array([[ 3, 13, 89, 62],
       [13, 33, 95, 31],
       [97, 26, 20, 50],
       [21, 82,  8,  8],
       [27, 89, 89, 28],
       [75, 46, 50, 28]])

In [46]:
np.flip(b)

array([[28, 50, 46, 75],
       [28, 89, 89, 27],
       [ 8,  8, 82, 21],
       [50, 20, 26, 97],
       [31, 95, 33, 13],
       [62, 89, 13,  3]])

In [47]:
# row flip
np.flip(b,axis=0)

array([[75, 46, 50, 28],
       [27, 89, 89, 28],
       [21, 82,  8,  8],
       [97, 26, 20, 50],
       [13, 33, 95, 31],
       [ 3, 13, 89, 62]])

In [48]:
#column flip
np.flip(b,axis=1)

array([[62, 89, 13,  3],
       [31, 95, 33, 13],
       [50, 20, 26, 97],
       [ 8,  8, 82, 21],
       [28, 89, 89, 27],
       [28, 50, 46, 75]])

np.put

its replace specific element of an array  with given values

In [49]:
a

array([46, 67, 24, 17, 81,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39,
       14,  8, 78, 39, 23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93,
       49, 11,  9, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

In [50]:
np.put(a,[0,1],[110,530])

In [51]:
a

array([110, 530,  24,  17,  81,   1,  71,  88,  12,  34,  89,  12,  75,
         7,  54,   1,  39,  14,   8,  78,  39,  23,  75,  14,  72,  95,
        89,  62,  90,  15,  11,  38,  91,  93,  49,  11,   9,  64,  55,
        65,  49,  15,  34,  44,  87,  36,  94,  53,  53,  13])

np.delete

In [52]:
#tempary
np.delete(a,[0,1,3,4]) # provide the index of an element which we want to delete

array([24,  1, 71, 88, 12, 34, 89, 12, 75,  7, 54,  1, 39, 14,  8, 78, 39,
       23, 75, 14, 72, 95, 89, 62, 90, 15, 11, 38, 91, 93, 49, 11,  9, 64,
       55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 13])

set functions

1)np.union1d

2)np.intersect1d

3)np.setdiff1d

4)np.setxor1d

5)np.in1d

np.union1d

In [53]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
np.intersect1d(m,n)

array([3, 4, 5])

In [56]:
np.setdiff1d(m,n) # output is number precent in "m" but not in "n"

array([1, 2])

In [58]:
np.setxor1d(m,n) # remove common numbers

array([1, 2, 6, 7])

In [59]:
np.in1d(m,2)

/tmp/ipykernel_2698/595628413.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,2)


array([False,  True, False, False, False])

np.clip

numpy.clip() function is used to clip(limit) the values in an array

In [60]:
a

array([110, 530,  24,  17,  81,   1,  71,  88,  12,  34,  89,  12,  75,
         7,  54,   1,  39,  14,   8,  78,  39,  23,  75,  14,  72,  95,
        89,  62,  90,  15,  11,  38,  91,  93,  49,  11,   9,  64,  55,
        65,  49,  15,  34,  44,  87,  36,  94,  53,  53,  13])

In [61]:
np.clip(a,a_min=14,a_max=94)

array([94, 94, 24, 17, 81, 14, 71, 88, 14, 34, 89, 14, 75, 14, 54, 14, 39,
       14, 14, 78, 39, 23, 75, 14, 72, 94, 89, 62, 90, 15, 14, 38, 91, 93,
       49, 14, 14, 64, 55, 65, 49, 15, 34, 44, 87, 36, 94, 53, 53, 14])

## ⚡ Quick Summary (1-Line Use)

- **Sort** → `np.sort()`  
- **Add** → `np.append()`  
- **Join** → `np.concatenate()`  
- **Unique** → `np.unique()`  
- **Condition** → `np.where()`  
- **Max index** → `np.argmax()`  
- **Sum** → `np.cumsum()`  
- **Stats** → `np.percentile()`, `np.histogram()`, `np.corrcoef()`  
- **Modify** → `np.put()`, `np.delete()`, `np.clip()`  
- **Set Ops** → `np.union1d()`, `np.intersect1d()`, `np.setdiff1d()`, `np.setxor1d()`  